ipynb-filters: [nbdev_filter]

project:
  type: website
  output-dir: _docs
  preview:
    port: 3000
    browser: false

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    toc-depth: 4

website:
  title: "Deep-Learning"
  site-url: "https://HafizAhmadHassan.github.io/mynbdev_cards/"
  description: "A sample how to create deck of cards lib using nbdev"
  execute: 
    enabled: false
  twitter-card: true
  open-graph: true
  reader-mode: true
  repo-branch: main
  repo-url: "https://github.com/HafizAhmadHassan/mynbdev_cards/"
  repo-actions: [issue]
  navbar:
    background: primary
    search: true
    left:
      - text: "Home"
        file: index.ipynb
      - sidebar:tutorials

    right:
      - icon: github
        href: "https://github.com/HafizAhmadHassan/mynbdev_cards/"
  sidebar:
      - id: tutorials
        title: "Tutorials"
        style: "floating"
        background: light
        collapse-level: 2
        contents:
        # navigation items
 
metadata-files: 
  - sidebar.yml
  - custom.yml