ipynb-filters: [nbdev_filter]

project:
  type: website
  output-dir: _docs
  preview:
    port: 3000
    browser: false

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    toc-depth: 4

website:
  title: "Deep Learning"
  site-url: "https://HafizAhmadHassan.github.io/mynbdev_cards/"
  description: ""
  execute: 
    enabled: false
  twitter-card: true
  open-graph: true
  reader-mode: true
  repo-branch: main
  repo-url: "https://github.com/HafizAhmadHassan/mynbdev_cards/"
  repo-actions: [issue]
  navbar:
    background: primary
    search: true
    collapse-below: lg
    left:
      - text: "Get Started"
        href: index.ipynb
    right:
      - icon: github
        href: "https://github.com/HafizAhmadHassan/mynbdev_cards/"
  sidebar:
    style: "floating"
    contents:
      - auto: "/*.ipynb"
      - section: Book
        contents: fastbook_updated2/*
metadata-files: 
  - sidebar.yml
  - custom.yml
