# AUTOGENERATED! DO NOT EDIT! File to edit: ../01_deck.ipynb.

# %% auto 0
__all__ = ['Deck']

# %% ../01_deck.ipynb 5
class Deck:
    def __init__(self):self.cards = [Card(s,r) for s in range(4) for r in range(1,14)]
    def __str__(self): return '; '.join(map(str,self.cards))
    def __len__(self): return len(self.cards)
    def __contains__(self,card): return card in self.cards
    
    __repr__=__str__

# %% ../01_deck.ipynb 9
@patch
def pop(self:Deck,idx:int=-1):
    return self.cards.pop(idx)
    

# %% ../01_deck.ipynb 14
@patch
def remove(self:Deck,
           card:Card):
    "Removes `card` from`deck or raises the exception if not there"
    self.cards.remove(card)
